version: "3"

services:
  frontend:
    build: ./package/client
    ports:
      - "3000:3000"
  backend:
    build: ./package/server
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"
